[build]
  command = "npx pnpm@7 install --store-dir=.pnpm --frozen-lockfile && cd packages/yyeva && npx pnpm@7 build && cd ../../projects/demo && npx pnpm@7 build"
  publish = "projects/demo/dist"

[build.environment]
  NPM_FLAGS="--version"
